spring:
  # database
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://3.37.174.68:5432/test
    url: jdbc:postgresql://localhost:5432/test
    username: 'postgres'
#    password: postgres
    password: '0000'
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: true
      generate-ddl: true
      format_sql: true
      show_sql: true
# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.demo.mybatis
  config: mybatis-config.xml







